[project]
name = "td-package"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.1"
dependencies = [
    
]

[[tool.uv.index]]
url = "https://test.pypi.org/simple/"
