[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tdp-ExampleComp"
version = "0.9"
dependencies = ["pydantic"]
authors = [{"name"= "Wieland Hilker", "email"= "Wieland@PlusPlus.One"}]
description = "We are just testing some stuff, ok?"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.11"
keywords = ["TouchDesigner", "2025.30060", "Test"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows"
]

[tool.setuptools.package-data]
"*" = ["*.tox"]

[project.urls]
TouchDesigner="https://derivative.ca"